import { MetrologyUser, MetrologyReport } from './types';

export const INITIAL_USERS: MetrologyUser[] = [
  {
    id: 'user-sa-001',
    license_number: 'NMC-SA-2026',
    company_name_kh: 'មជ្ឈមណ្ឌលមាត្រាសាស្ត្រជាតិ (NMC) នៃក្រសួងឧស្សាហកម្ម វិទ្យាសាស្ត្រ បច្ចេកវិទ្យា និងនវានុវត្តន៍',
    company_name_en: 'National Metrology Center of Cambodia',
    address: 'មហាវិថីសហព័ន្ធរុស្ស៊ី ភ្នំពេញ កម្ពុជា',
    phone: '023 884 123',
    email: 'info@nmc.gov.kh',
    legal_representative: 'ឯកឧត្តម ប្រធានមជ្ឈមណ្ឌល',
    representative_position: 'អគ្គនាយក',
    username: 'superadmin',
    password: 'admin123',
    role: 'superadmin',
    can_view: true,
    can_edit: true,
    can_save: true,
    can_delete: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'user-ad-001',
    license_number: 'NMC-AD-2026',
    company_name_kh: 'នាយកដ្ឋានមាត្រាសាស្ត្រឧស្សាហកម្ម',
    company_name_en: 'Department of Industrial Metrology',
    address: 'មហាវិថីសហព័ន្ធរុស្ស៊ី ភ្នំពេញ កម្ពុជា',
    phone: '012 345 678',
    email: 'inspection@nmc.gov.kh',
    legal_representative: 'លោក ប្រធាននាយកដ្ឋាន',
    representative_position: 'ប្រធាននាយកដ្ឋាន',
    username: 'admin',
    password: 'admin123',
    role: 'admin',
    can_view: true,
    can_edit: true,
    can_save: true,
    can_delete: true,
    created_at: '2026-01-02T00:00:00Z',
    admin_can_add_company_user: true,
    admin_can_add_admin_user: true,
    admin_can_edit_users: true,
    admin_can_deactivate_users: true,
    admin_can_view_all_users: true,
    is_active: true,
  },
  {
    id: 'user-co-001',
    license_number: 'LIC-2026-001',
    company_name_kh: 'ក្រុមហ៊ុន មាត្រាសាស្ត្រ បូកគោ',
    company_name_en: 'Bokor Metrology Corp',
    address: 'ផ្ទះលេខ ១២A ផ្លូវជាតិលេខ ៣ ខេត្តកំពត',
    phone: '016 999 888',
    email: 'contact@bokormetrology.com',
    legal_representative: 'លោក លី ម៉េង',
    representative_position: 'នាយកប្រតិបត្តិ',
    username: 'company01',
    password: 'LIC001',
    role: 'company',
    can_view: true,
    can_edit: true,
    can_save: true,
    can_delete: true,
    created_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'user-co-002',
    license_number: 'LIC-2026-002',
    company_name_kh: 'សហគ្រាសវាស់វែងអង្គរ',
    company_name_en: 'Angkor Measurement Enterprises',
    address: 'ផ្លូវជាតិលេខ ៦ ក្រុងសៀមរាប ខេត្តសៀមរាប',
    phone: '011 222 333',
    email: 'angkor_measure@gmail.com',
    legal_representative: 'អ្នកស្រី សុខ ចិន្តា',
    representative_position: 'អគ្គនាយិកា',
    username: 'company02',
    password: 'LIC002',
    role: 'company',
    can_view: true,
    can_edit: true,
    can_save: false,
    can_delete: false,
    created_at: '2026-03-10T00:00:00Z',
  },
];

export const INITIAL_REPORTS: MetrologyReport[] = [
  {
    id: 'rep-001',
    user_id: 'user-co-001',
    license_number: 'LIC-2026-001',
    company_name_kh: 'ក្រុមហ៊ុន មាត្រាសាស្ត្រ បូកគោ',
    customer_name: 'រោងចក្រស៊ីម៉ងត៍កម្ពុជាចក្រីទីង',
    customer_address: 'ផ្លូវជាតិលេខ ៣ ស្រុកទឹកឈូ ខេត្តកំពត',
    measuring_instrument: 'ជញ្ជីងរថយន្តអេឡិចត្រូនិច ១០០ តោន (Truck Scale 100T)',
    instrument_serial_number: 'TS2026-99182',
    scope_of_weight_measure: 'សហការវាស់ស្ទង់ពី ០ ទៅ ១០០,០០០ គីឡូក្រាម',
    spare_parts: 'ឧបករណ៍សញ្ញាអេឡិចត្រូនិច (Weight Indicator Model XK3190)',
    spare_part_serial_number: 'IND-9812A',
    service_type: 'Installation',
    service_start_date: '2026-05-02',
    service_end_date: '2026-05-05',
    report_month: '05',
    report_year: '2026',
    created_at: '2026-05-05T08:30:00Z',
    updated_at: '2026-05-05T08:30:00Z',
  },
  {
    id: 'rep-002',
    user_id: 'user-co-001',
    license_number: 'LIC-2026-001',
    company_name_kh: 'ក្រុមហ៊ុន មាត្រាសាស្ត្រ បូកគោ',
    customer_name: 'ស្ថានីយប្រេងឥន្ធនៈតេលាស្ទឹងមានជ័យ',
    customer_address: 'ផ្លូវ ២៧១ សង្កាត់ស្ទឹងមានជ័យ ភ្នំពេញ',
    measuring_instrument: 'ទូរចាក់ប្រេងសាំង ៤ ក្បាលចាក់ (TELA Fuel Dispenser)',
    instrument_serial_number: 'DISP-AB-7741',
    scope_of_weight_measure: 'លំហូររង្វាស់ពី ៥ ទៅ ៨០ លីត្រ/នាទី',
    spare_parts: 'ស្នប់វាស់សម្ពាធលំហូរ (Flow Meter Module V2)',
    spare_part_serial_number: 'FM-77119-Z',
    service_type: 'Repair',
    service_start_date: '2026-05-10',
    service_end_date: '2026-05-11',
    report_month: '05',
    report_year: '2026',
    created_at: '2026-05-11T14:20:00Z',
    updated_at: '2026-05-11T14:20:00Z',
  },
  {
    id: 'rep-003',
    user_id: 'user-co-001',
    license_number: 'LIC-2026-001',
    company_name_kh: 'ក្រុមហ៊ុន មាត្រាសាស្ត្រ បូកគោ',
    customer_name: 'ក្រុមហ៊ុន ភ្នំពេញការ៉ាត់ ហ្គោល',
    customer_address: 'ផ្សារធំថ្មី ខណ្ឌដូនពេញ ភ្នំពេញ',
    measuring_instrument: 'ជញ្ជីងវិភាគគ្រឿងអលង្ការបច្ចេកវិទ្យាខ្ពស់ (Jewelry Analytical Balance)',
    instrument_serial_number: 'BAL-KH-2026-03',
    scope_of_weight_measure: 'លទ្ធភាពថ្លឹងពី ០.០០១ ក្រាម ទៅ ៣២០ ក្រាម',
    spare_parts: 'បន្ទះឈីបសេនស័រវាស់បន្ទុក (Loadcell Sensor Board Block)',
    spare_part_serial_number: 'LC-AM-990',
    service_type: 'Manufacture',
    service_start_date: '2026-04-12',
    service_end_date: '2026-04-20',
    report_month: '04',
    report_year: '2026',
    created_at: '2026-04-20T09:15:00Z',
    updated_at: '2026-04-20T09:15:00Z',
  },
  {
    id: 'rep-004',
    user_id: 'user-co-002',
    license_number: 'LIC-2026-002',
    company_name_kh: 'សហគ្រាសវាស់វែងអង្គរ',
    customer_name: 'កសិដ្ឋានស្រូវអង្ករសុវណ្ណភូមិ',
    customer_address: 'ស្រុកក្រឡាញ់ ខេត្តសៀមរាប',
    measuring_instrument: 'ជញ្ជីងថ្លឹងស្រូវបាវទម្ងន់ ១តោន (Platform Scale 1T)',
    instrument_serial_number: 'ANG-P1000-88',
    scope_of_weight_measure: 'លទ្ធភាពថ្លឹងរហូតដល់ ១,០០០ គីឡូក្រាម',
    spare_parts: 'ប៊ូតុងបញ្ជាបន្ទុក និងអេក្រង់ LED',
    spare_part_serial_number: 'DISP-L88',
    service_type: 'Installation',
    service_start_date: '2026-05-15',
    service_end_date: '2026-05-16',
    report_month: '05',
    report_year: '2026',
    created_at: '2026-05-16T11:00:00Z',
    updated_at: '2026-05-16T11:00:00Z',
  },
  {
    id: 'rep-005',
    user_id: 'user-co-002',
    license_number: 'LIC-2026-002',
    company_name_kh: 'សហគ្រាសវាស់វែងអង្គរ',
    customer_name: 'មន្ទីរពេទ្យបង្អែកសៀមរាប',
    customer_address: 'ផ្លូវមន្ទីរពេទ្យ ក្រុងសៀមរាប ខេត្តសៀមរាប',
    measuring_instrument: 'ជញ្ជីងវេជ្ជសាស្ត្រវាស់កម្ពស់និងទម្ងន់ទារក (Pediatric Scale/Infant Measure)',
    instrument_serial_number: 'MED-INF-120',
    scope_of_weight_measure: 'ថ្លឹងទម្ងន់ពី ០ ទៅ ២០ គីឡូក្រាម, កម្រិតលំអៀង ១០ ក្រាម',
    spare_parts: 'បន្ទះត្រួតពិនិត្យភាពគ្លាតឌីជីថល (Digital Mainboard Seka)',
    spare_part_serial_number: 'SEKA-MB-003',
    service_type: 'Repair',
    service_start_date: '2026-05-20',
    service_end_date: '2026-05-21',
    report_month: '05',
    report_year: '2026',
    created_at: '2026-05-22T04:10:00Z',
    updated_at: '2026-05-22T04:10:00Z',
  },
];

export function isDemoDataEnabled(): boolean {
  if (typeof window !== 'undefined') {
    const host = window.location.hostname;
    if (host === 'metrologyreport.vercel.app') {
      return false;
    }
    if (host === 'localhost' || host === '127.0.0.1' || host.startsWith('192.168.')) {
      return true;
    }
  }
  const meta = import.meta as any;
  if (meta.env?.DEV === true) {
    return true;
  }
  if (meta.env?.VITE_ENABLE_DEMO_DATA === 'true') {
    return true;
  }
  return false;
}

